on: [push]
name: Docker
jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: docker/login-action@v1
        with:
          username: tdspora
          password: ${{ secrets.DOCKER_HUB_TOKEN }}        
      - name: Set up Docker Buildx
        # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: docker/setup-buildx-action@v1

      - name: Docker meta (Training)
        id: docker_meta_train
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: tdspora/syngen-train
          tag-custom: latest
          tag-semver: |
            {{raw}}
      - name: Docker meta (Inference)
        id: docker_meta_infer
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: tdspora/syngen-infer
          tag-custom: latest
          tag-semver: |
            {{raw}}
      - name: Build and push (Training)
        # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./ml-training.dockerfile
          push: true
          tags: ${{ steps.docker_meta_train.outputs.tags }}
          labels: ${{ steps.docker_meta_train.outputs.labels }}
          cache-from: type=registry,ref=tdspora/syngen-train:buildcache
          cache-to: type=registry,ref=tdspora/syngen-train:buildcache,mode=max
      - name: Build and push (Inference)
        # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./ml-inference.dockerfile
          push: true
          tags: ${{ steps.docker_meta_infer.outputs.tags }}
          labels: ${{ steps.docker_meta_infer.outputs.labels }}
          cache-from: type=registry,ref=tdspora/syngen-infer:buildcache
          cache-to: type=registry,ref=tdspora/syngen-infer:buildcache,mode=max
