on: issue_comment
name: Docker
jobs:
  Docker-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}        
      - name: Set up Docker Buildx
        # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: docker/setup-buildx-action@v1
      - name: Get version from tags
        id: gen_tags
        # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
            TAGS_TRAIN='["${{ secrets.DOCKER_HUB_USERNAME }}/syngen-train:latest","${{ secrets.DOCKER_HUB_USERNAME }}/syngen-train:'${GITHUB_REF/refs\/tags\//}'"]'
            TAGS_INFER='["${{ secrets.DOCKER_HUB_USERNAME }}/syngen-infer:latest","${{ secrets.DOCKER_HUB_USERNAME }}/syngen-infer:'${GITHUB_REF/refs\/tags\//}'"]'
          else
            TAGS_TRAIN='["${{ secrets.DOCKER_HUB_USERNAME }}/syngen-train:latest"]'
            TAGS_INFER='["${{ secrets.DOCKER_HUB_USERNAME }}/syngen-infer:latest"]'
          fi
          echo -e '::set-output name=tags_train::'$TAGS_TRAIN \n
          echo '::set-output name=tags_infer::'$TAGS_INFER
      - name: Build and push (Training)
        # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.ml-training
          push: true
          tags: ${{ fromJson(steps.gen_tags.outputs.tags_train) }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/syngen-train:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/syngen-train:buildcache,mode=max
      - name: Build and push (Inference)
        # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.ml-inference
          push: true
          tags: ${{ fromJson(steps.gen_tags.outputs.tags_infer) }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/syngen-infer:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/syngen-infer:buildcache,mode=max
